// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBtn: typeof import('./src/components/global/AppBtn.vue')['default']
    AppSearchInput: typeof import('./src/components/global/AppSearchInput.vue')['default']
    DocumentPanel: typeof import('./src/components/document/DocumentPanel.vue')['default']
    DocumentSearch: typeof import('./src/components/document/DocumentSearch.vue')['default']
    DocumentView: typeof import('./src/components/document/DocumentView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/global/SvgIcon.vue')['default']
  }
}
